### ISSUE TITLE
Fix white space at top or bottom of page on mobile

### ISSUE THREAD

**Issue by coreyzev** [warfare-plugins/social-warfare#654] opened 2018-09-28 03:43 UTC
## Notes for testers

**What we expect**
When using mobile floating buttons, there should be no unintentional whitespace. 

**How to Test**

1. In Social Warfare -> Display -> Floating Share Buttons, set On Mobile to "top of screen." Save changes.
2. Visit a post on mobile. As soon as the page loads, there should be no whitespace at the top of the page. And as you scroll through the page, there should not be any whitespace at the top of the screen.
3. Change On Moble to "bottom of screen." Save changes.
4. Visit the same post on mobile. Same as step 2, but for bottom instead of top. 

If something does not go as described above, please let us know in the comments. 
Once you have finished testing, please give this comment a thumbs up. 

### end notes
IREF: 217615, 221899

Some users are seeing extra padding at the top or bottom of their pages when in mobile mode. This space is created to make space for the floating buttons panel. 

> 3.3.3 causes format error on mobile display. It creates an empty space at the top of the page for displaying another social warfare bar, but I only display it at the bottom of the page. So all it does is push my page down and leave an empty space at the top of the page.

> any page that is marked as “Webpage” in the schema, is being assigned an inline style when viewing in mobile sizes of “padding-top: 50px;”

**Comment by ckmahoney** [comment] 2018-10-25 17:54
Various commits on other mobile button issues appear to have resolved this bug.

**Comment by hblomgren** [comment] 2018-11-13 20:38
New issue found. Floating sharing buttons do not appear at all unless you choose the "float left/right" option.

Float Top and Float Bottom do not output any floating share buttons. Normal buttons are displayed fine but the floating ones are not.

**Comment by Nicholas-Cardot** [comment] 2018-11-13 20:42
I've replicated this as well. I don't see a DOM element being created whatsoever for the floating panel when it is set to top or bottom so there is nothing to show/hide at all. I also don't see any console errors. 

Perhaps a floating position attribute is off somewhere. I'll check on that real quick.

**Comment by Nicholas-Cardot** [comment] 2018-11-13 21:17
```		if (!socialWarfare.panels.staticHorizontal.length || !socialWarfare.panels.staticHorizontal[0].length) {
			return;
		}```

It appears that this conditional is failin even when buttons are indeed present on the post.

**Comment by Nicholas-Cardot** [comment] 2018-11-13 21:21
Okay, I've now created the floater bar, but I it won't hide/show yet.

**Comment by ckmahoney** [comment] 2018-11-14 20:41
When mobile buttons are OFF, there is still whitespace at the top of the screen where they would have been.

**Comment by Gene-W** [comment] 2018-11-14 22:42
Testing this in Chrome on a tablet and it's displaying correctly. I'm not seeing the white space with buttons off.

**Comment by ckmahoney** [comment] 2018-11-15 17:04
Thanks @Gene-W. 
Depending on if your theme has an element called "#wpadminbar", you may or may not have had the whitespace. Many themes have it, some don't. 

I just pushed changes that patch it and will update the zips with fresh code in a couple hours.

**Comment by hblomgren** [comment] 2018-11-27 19:36
Tried it on latest version of the core plugin. Works as intended now. So from my experience so far this issue is now fixed.

**Closed** 2018-11-29 02:15 UTC
Labels: Bug Report, READY FOR TESTING
