### ISSUE TITLE
Pinterest description not showing in Safari or Edge

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#723] opened 2019-08-16 16:36 UTC
When using the basic Pinterest button in Safari the title of the blog post/info does not show.
![pin](https://user-images.githubusercontent.com/39499655/63183129-15883f00-c009-11e9-94de-ee4c7c5b9d5b.jpg)
See internal #317587 and 318490 - but there are several more reports.

**Comment by Nicholas-Cardot** [comment] 2020-02-22 00:14
Closing this as a duplicate or near duplicate of some other issues.

**Closed by Nicholas-Cardot** 2020-02-22 00:14 UTC
Labels: Bug Report
