### ISSUE TITLE
Buttons not showing / invisble

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#210] opened 2016-07-14 16:12 UTC
Some users are reporting that after upgrading to 2.0+ the buttons aren't showing up on posts. Upon inspection, it looks like they are present but not transitioning from 0% opacity to 100% opacity for some reason. 

iTag: invisible

**Comment by batmanbldr** [comment] 2016-07-15 14:59
I am also experiencing no buttons showing at all. But with a mouse over where they should be it only shows which button it is in status bar.

**Comment by genork** [comment] 2016-07-16 13:39
I see no buttons and the body of my older posts disappear - when I turn off the plugin the older posts are fine.

**Comment by annaloverus** [comment] 2016-07-16 18:52
I've got the same problem!

**Comment by hammondb** [comment] 2016-07-19 20:01
Exact same issue.  Just sent in a support request but will follow this thread to see if a solution is found.

**Comment by Nicholas-Cardot** [comment] 2016-07-20 20:24
Can you all confirm a few things to help me narrow down what's happening?

1. Are you using a caching plugin? If so, which one?
2. If you temporarily disable the caching plugin (just for testing), does the problem go away?
3. If you add our javascript (/wp-content/plugins/social-warfare/script.min.js) to the list of excluded files not to be cached or minified, does the problem go away?

Thanks!

**Comment by Nicholas-Cardot** [comment] 2016-07-21 20:42
We just had a user report that this is only happening when the Pin Image Hover Button is activated. Can any of you turn the pin button off and let me know if this fixes the issue for you? If so, that allows me to narrow it down and I'll know what I need to fix to make them both play nicely together. Thanks!

**Comment by hammondb** [comment] 2016-07-21 23:20
@Nicholas-Cardot 

Nope, still had the same issue.  Rolled back to 1.4.8 at @DustinWStout recommended and it works as it did before no problem.  Thank you both for your ongoing support here!  You both rock!

**Comment by Nicholas-Cardot** [comment] 2016-07-22 17:44
@hammondb Okay. Thanks for testing that out for me and for being willing to roll back in the mean time.

**Comment by Nicholas-Cardot** [comment] 2016-08-02 20:06
I may have this fixed in the current version. Anyone want to install and test it out?

**Closed** 2016-08-04 19:14 UTC
Labels: Bug / Glitch

**Comment by hammondb** [comment] 2016-08-16 23:28
I am still having the exact same issue...

**Comment by RobinStroh** [comment] 2016-08-25 04:16
I upgraded one of the sites with the mystery of the hidden social share icons to version 2.0.5. The mystery persists. Please let me know if there has been any progress.

**Comment by Nicholas-Cardot** [comment] 2016-08-25 12:54
For invisible buttons, here is what is happening in every instance we've encountered so far. 

First, check your browser's console (in Chrome or Firefox) by right-clicking anywhere on the page and select "Inspect Element." Upon doing so, the developer tools for the browser will open. Locate the "Console" tab and click on it. This will list any errors.

It will say something like blahblah.outerHTML is not a function. This is caused by 1 of 3 things.

1: You are using an old version and need to update to 2.0.5.

2: Check if jQuery is being enqueued both before and after the script for our plugin is being enqueued.

jQuery has in it the ability to create new jQuery functions. In fact, we use a custom jQuery function in our plugin. So if jQuery, for example, offers 200 functions to us, I've now declared a 201st function that meets the needs of our plugin.

However, the browser is saying that my function doesn't exists. Here's why. The jQuery function library got built on the first jQuery request. The one built into WordPress. Then I declared the new functions that I need for my plugin. Then your second request for jQuery deleted the existing library and rebuilt it from scratch effectively deleting the function that I needed. Then my script attempted to use the function (to size and show the buttons) but the function didn't exist so it threw an error and the buttons stay hidden.
 
3. The site is using a minification process that renames functions. I've seen some caching plugins that literally rename the functions in our plugin. The problem is that some of the functions (primarily the jQuery function) cannot be renamed. It literally must be named jQuery because it relies on the jQuery library. If renamed, it ceases to reference the jQuery library and immediately breaks. Simply add "/wp-content/plugins/social-warfare/script.min.js" to the list of files in your caching or minification plugin to be excluded from minification and it should fix it.

**Comment by RobinStroh** [comment] 2016-08-26 12:38
Thank you, Nicholas, for the detailed description! You helped me find the problem. It turned out to be the   ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js that was included to "make-tel-link" for Chrome on mobile. When I eliminated the script, the buttons appeared!

**Comment by Haikuka** [comment] 2018-06-01 04:05
I know it's been a while since this was posted, but could you help me with the solution? I'm not sure how to remove the jQuery script on my site (rather new to WordPress). I'm having the same issue with the buttons not showing up on Chrome mobile. They show up on the default Samsung internet browser though.

**Comment by VR51** [comment] 2018-06-01 17:04
@Haikuka The plugin has been through a few code edits and rewrites since this was first posted and last commented on (Aug. 2016). You will be better off opening a fresh bug report. The issue you are experiencing is probably unrelated to the initial bug described in this thread.

However, try a website cache refresh and a browser cache refresh. This usually resolves Social Warfare display issues. Secondly, make sure the web server has set the correct file and directory permissions for the plugin's upload directory; they sometimes change from their defaults.

**Comment by Haikuka** [comment] 2018-06-07 04:42
@VR51 Thank you! I shall follow your advice!
