### ISSUE TITLE
User Request: Add images to "click to tweet"

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#182] opened 2016-05-27 01:31 UTC
### User has requested:

> I'm curious to know if there's a simple, clean way to add an image to the "Click to Tweet"? Is that a feature that I'm missing?

**Comment by Nicholas-Cardot** [comment] 2016-05-27 15:03
We can't add images without first adding a Twitter oauth application layer wherein the user would pre-authorize our plugin to upload images to the users account. However, the user can already add images by uploading them directly to Twitter and then copy and pasting the pic.twit link into the tweet portion of the click to tweet.

**Comment by Nicholas-Cardot** [comment] 2016-05-29 12:45
This is essentially the same as the request to add images to the Custom Tweet. I'm just going to delete this task and when I get around to building the one for Custom Tweets, it will be the exact same functionality for this. As such, I'm just going to consider this as a duplicate of that issue.

**Closed** 2016-05-29 12:45 UTC
Labels: invalid

**Comment by aaronbrosef** [comment] 2016-06-01 01:35
My bad!
For anyone coming across this thread, you want this ticket: [https://github.com/warfare-plugins/social-warfare/issues/118](https://github.com/warfare-plugins/social-warfare/issues/118)
