### ISSUE TITLE
Conflict with Widget CSS Classes Plugin causes runaway "undefined" error in Firebox console

### ISSUE THREAD

**Issue by bghouse** [warfare-plugins/social-warfare#158] opened 2016-05-08 22:46 UTC
My apologies for taking so long to come back on this issue - I wanted to make sure I thoroughly tested this by turning off every plugin until I could reproduce this.

The conflict is with the Widget CSS Classes Plugin (found here:  https://wordpress.org/plugins/widget-css-classes/).  When this plugin is active at the same time as Social Warfare, the js script shows "undefined" in the Firebug Console a couple of times (see screenshot).

The very last one will keep climbing in number - the highest I've let it get is over 500 - it just doesn't stop.  
<img width="1339" alt="screen shot 2016-05-08 at 3 29 38 pm" src="https://cloud.githubusercontent.com/assets/580021/15100835/099f977a-1534-11e6-9067-a8fb2d86c05c.png">

**Comment by bghouse** [comment] 2016-05-08 22:54
Update:  I can also confirm that the floating left side bar will not display is the Widget CSS Classes Plugin is active.

**Comment by DustinWStout** [comment] 2016-05-13 19:31
Hi @bghouse! We're trying to recreate this on our development site and are unable to do so. We have both _Social Warfare_ and _Widget CSS Classes_ activated without any console errors or unintended behavior. Can you give us a little more info so we can reproduce this error?

**Comment by Nicholas-Cardot** [comment] 2016-05-13 19:40
We've been able to replicate this issue now and should have this fixed within the next few minutes.

**Closed** 2016-05-13 19:57 UTC
Labels: Bug / Glitch

**Comment by bghouse** [comment] 2016-06-01 16:41
Wonderful - thanks!
