### ISSUE TITLE
Browser resize causes button distortion

### ISSUE THREAD

**Issue by shadowlocked** [warfare-plugins/social-warfare#246] opened 2016-08-21 11:34 UTC
Since the previous post which raised this issue doesn't seem to be here now, wanted to mention that the browser resize issue is unresolved.

Some users seem to have experienced very small button sizes upon resize. My experience with 2.0-2.04 is that on resize the buttons distort to absurd horizontal lengths, and I am waiting for news of a fix before applying the update to the live site rather than the staging site.

The problem is illustrated here:

https://www.youtube.com/watch?v=N9gHU85KQjk

**Comment by Nicholas-Cardot** [comment] 2016-08-21 14:15
@shadowlocked This is a duplicate of issue #236. This was fixed in a soft update. What that means is that we didn't iterate the version number up to 2.0.5 but you can get the new fixed version by simply uninstalling the plugin and reinstalling it from the WordPress repository (the search menu on the plugins page of your WordPress admin). Please update and let me know if it's all taken care of.

**Comment by shadowlocked** [comment] 2016-08-22 06:25
Thank you for this information. I don't know why I didn't receive an email update to the other post. I have installed the latest version on the staging site and will give it a few days there before going to live. I can see that quite some work is going on behind the scenes to make the buttons behave during a resize, and just want to check performance before moving to live. I'll come back on this shortly.

**Comment by shadowlocked** [comment] 2016-08-22 06:42
On this update, tne thing I notice testing the Hacker News plugin is that it fills in the title submission box using + signs instead of spaces. Ycombinator punishes poor submitters quite badly, so I'm not keen to test it further. Is there any comment on this.

![hnews](https://cloud.githubusercontent.com/assets/3078715/17845721/e97e887e-683b-11e6-9067-d0379898a386.png)

**Comment by DustinWStout** [comment] 2016-10-20 20:58
Solved with next update.

**Closed** 2016-10-20 20:58 UTC
