### ISSUE TITLE
Images are not loaded or disappear. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#576] opened 2018-07-17 22:00 UTC
TicketID 185980

We have had two reports of this, but have not yet been provided links or logins. 

I suspect it is a result of a javascript error which breaks the image loading script.

**Comment by rangerdth** [comment] 2018-07-23 16:56
I ran into this today. The issue I found was with: style.min.css
Specifically: 
div.sw-pinit {
   display: table!important;
   line-height: 0;
   position: relative!important
}

You can: turn "off" the Image Hover Pin Button in the plugin "Display" menu.
Or, you can comment out: position: relative!important the page will load fine.

**Comment by rangerdth** [comment] 2018-08-10 14:34
I can probably provide a link for some quick testing if you're still interested.

**Comment by ckmahoney** [comment] 2018-08-14 17:25
Hi @rangerdth,

We released version 3.2.0 of Social Warfare and Pro yesterday. I think this issue was probably related to JS errors being thrown in 3.1.1.

Can you please update to 3.2.0 and let me know if this is still a problem? If so please provide a link to the site where the problem is happening. 

Thanks - cortland

**Comment by Nicholas-Cardot** [comment] 2018-08-22 00:02
@rangerdth That's why we marked this issue as "Drop". Unless we here from someone that it is still happening or get some more information that allows us to make some forward progress, we will be closing this issue at the end of the week. What exactly do you mean about the hover stuff though? Is there another bug we need to know about?

**Comment by rangerdth** [comment] 2018-08-22 00:32
I think I was incorrect in my explanation. I was thinking the 'pinit' button was supposed to overlay the top of an page/post, whereas now it's just on the page/post (on the side or above/below).
The issue is still happening on the previous version, but the images are displaying with 3.2.2 on my test site. I'll upgrade my production site and confirm.

**Comment by Nicholas-Cardot** [comment] 2018-08-22 00:39
@rangerdth We have a beta testers community including a slack chat room that makes it much easier to discuss stuff like this. Is that something that you might be interested in? Signing up and staying active includes a few perks like some free licenses and whatnot.

**Comment by rangerdth** [comment] 2018-08-22 00:42
definitely!

**Comment by Nicholas-Cardot** [comment] 2018-08-22 00:45
You can sign up here. I'll give Dustin your name as he's the one that does the vetting and we'll get you right in. We can probably have you in the slack chat community as early as tomorrow. :-) 

https://warfareplugins.com/beta-tester-application/

**Closed** 2018-08-22 19:55 UTC
Labels: Bug Report, Drop
